### PR TITLE
Remove Symbol dependency and unused Babel external helpers

### PR DESCRIPTION
**Pull request by razh**
The Babel for-of transform requires a Symbol polyfill.

https://babeljs.io/docs/plugins/transform-es2015-for-of/

This removes for-of in favor of `Array.prototype.forEach` (and `ImmutableList#forEach`), which results in a smaller file-size.

| File size | Before | After |
|---|---|---|
| `dist/vue-dragula.js` | 81.67kb | 74.78kb |
| `dist/vue-dragula.min.js` | 35.34kb | 32.96kb |

<details>
<summary>Diff of dist/vue-dragula.js</summary>

```diff
diff --git a/dist/vue-dragula.js b/dist/vue-dragula.js
index 5157949..fa0a9b9 100644
--- a/dist/vue-dragula.js
+++ b/dist/vue-dragula.js
@@ -1071,125 +1071,6 @@ var require$$0$3 = Object.freeze({
 
 	var dragula$1 = interopDefault(dragula);
 
-	var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
-	  return typeof obj;
-	} : function (obj) {
-	  return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
-	};
-
-	var asyncGenerator = function () {
-	  function AwaitValue(value) {
-	    this.value = value;
-	  }
-
-	  function AsyncGenerator(gen) {
-	    var front, back;
-
-	    function send(key, arg) {
-	      return new Promise(function (resolve, reject) {
-	        var request = {
-	          key: key,
-	          arg: arg,
-	          resolve: resolve,
-	          reject: reject,
-	          next: null
-	        };
-
-	        if (back) {
-	          back = back.next = request;
-	        } else {
-	          front = back = request;
-	          resume(key, arg);
-	        }
-	      });
-	    }
-
-	    function resume(key, arg) {
-	      try {
-	        var result = gen[key](arg);
-	        var value = result.value;
-
-	        if (value instanceof AwaitValue) {
-	          Promise.resolve(value.value).then(function (arg) {
-	            resume("next", arg);
-	          }, function (arg) {
-	            resume("throw", arg);
-	          });
-	        } else {
-	          settle(result.done ? "return" : "normal", result.value);
-	        }
-	      } catch (err) {
-	        settle("throw", err);
-	      }
-	    }
-
-	    function settle(type, value) {
-	      switch (type) {
-	        case "return":
-	          front.resolve({
-	            value: value,
-	            done: true
-	          });
-	          break;
-
-	        case "throw":
-	          front.reject(value);
-	          break;
-
-	        default:
-	          front.resolve({
-	            value: value,
-	            done: false
-	          });
-	          break;
-	      }
-
-	      front = front.next;
-
-	      if (front) {
-	        resume(front.key, front.arg);
-	      } else {
-	        back = null;
-	      }
-	    }
-
-	    this._invoke = send;
-
-	    if (typeof gen.return !== "function") {
-	      this.return = undefined;
-	    }
-	  }
-
-	  if (typeof Symbol === "function" && Symbol.asyncIterator) {
-	    AsyncGenerator.prototype[Symbol.asyncIterator] = function () {
-	      return this;
-	    };
-	  }
-
-	  AsyncGenerator.prototype.next = function (arg) {
-	    return this._invoke("next", arg);
-	  };
-
-	  AsyncGenerator.prototype.throw = function (arg) {
-	    return this._invoke("throw", arg);
-	  };
-
-	  AsyncGenerator.prototype.return = function (arg) {
-	    return this._invoke("return", arg);
-	  };
-
-	  return {
-	    wrap: function (fn) {
-	      return function () {
-	        return new AsyncGenerator(fn.apply(this, arguments));
-	      };
-	    },
-	    await: function (value) {
-	      return new AwaitValue(value);
-	    }
-	  };
-	}();
-
 	var classCallCheck = function (instance, Constructor) {
 	  if (!(instance instanceof Constructor)) {
 	    throw new TypeError("Cannot call a class as a function");
@@ -1214,31 +1095,6 @@ var require$$0$3 = Object.freeze({
 	  };
 	}();
 
-	var get = function get(object, property, receiver) {
-	  if (object === null) object = Function.prototype;
-	  var desc = Object.getOwnPropertyDescriptor(object, property);
-
-	  if (desc === undefined) {
-	    var parent = Object.getPrototypeOf(object);
-
-	    if (parent === null) {
-	      return undefined;
-	    } else {
-	      return get(parent, property, receiver);
-	    }
-	  } else if ("value" in desc) {
-	    return desc.value;
-	  } else {
-	    var getter = desc.get;
-
-	    if (getter === undefined) {
-	      return undefined;
-	    }
-
-	    return getter.call(receiver);
-	  }
-	};
-
 	var inherits = function (subClass, superClass) {
 	  if (typeof superClass !== "function" && superClass !== null) {
 	    throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
@@ -1848,37 +1704,16 @@ var require$$0$3 = Object.freeze({
 	  }, {
 	    key: 'on',
 	    value: function on() {
+	      var _this2 = this;
+
 	      var handlerConfig = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
 
 	      this.log('on (events) ', handlerConfig);
-	      var handlerNames = Object.keys(handlerConfig);
-
-	      var _iteratorNormalCompletion = true;
-	      var _didIteratorError = false;
-	      var _iteratorError = undefined;
-
-	      try {
-	        for (var _iterator = handlerNames[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
-	          var handlerName = _step.value;
-
-	          var handlerFunction = handlerConfig[handlerName];
-	          this.log('$on', handlerName, handlerFunction);
-	          this.eventBus.$on(handlerName, handlerFunction);
-	        }
-	      } catch (err) {
-	        _didIteratorError = true;
-	        _iteratorError = err;
-	      } finally {
-	        try {
-	          if (!_iteratorNormalCompletion && _iterator.return) {
-	            _iterator.return();
-	          }
-	        } finally {
-	          if (_didIteratorError) {
-	            throw _iteratorError;
-	          }
-	        }
-	      }
+	      Object.keys(handlerConfig).forEach(function (handlerName) {
+	        var handlerFunction = handlerConfig[handlerName];
+	        _this2.log('$on', handlerName, handlerFunction);
+	        _this2.eventBus.$on(handlerName, handlerFunction);
+	      });
 	    }
 	  }, {
 	    key: 'destroy',
@@ -2139,6 +1974,8 @@ var require$$0$3 = Object.freeze({
 	    }, {
 	      key: 'createService',
 	      value: function createService() {
+	        var _this = this;
+
 	        var serviceOpts = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
 
 	        logServiceConfig('createService', serviceOpts);
@@ -2157,44 +1994,22 @@ var require$$0$3 = Object.freeze({
 	        }
 
 	        logServiceConfig('names', names);
-	        var _iteratorNormalCompletion = true;
-	        var _didIteratorError = false;
-	        var _iteratorError = undefined;
-
-	        try {
-	          for (var _iterator = names[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
-	            var _name = _step.value;
-
-	            var createOpts = {
-	              name: _name,
-	              eventBus: eventBus,
-	              options: opts
-	            };
-	            logServiceConfig('create DragulaService', _name, createOpts);
-	            this._serviceMap[_name] = _createService(createOpts);
-
-	            // use 'default' drakes if none specified
-	            if (!drakes.default) {
-	              drakes.default = drake || true;
-	            }
-
-	            this.drakesFor(_name, drakes);
+	        names.forEach(function (name) {
+	          var createOpts = {
+	            name: name,
+	            eventBus: eventBus,
+	            options: opts
+	          };
+	          logServiceConfig('create DragulaService', name, createOpts);
+	          _this._serviceMap[name] = _createService(createOpts);
+
+	          // use 'default' drakes if none specified
+	          if (!drakes.default) {
+	            drakes.default = drake || true;
 	          }
-	        } catch (err) {
-	          _didIteratorError = true;
-	          _iteratorError = err;
-	        } finally {
-	          try {
-	            if (!_iteratorNormalCompletion && _iterator.return) {
-	              _iterator.return();
-	            }
-	          } finally {
-	            if (_didIteratorError) {
-	              throw _iteratorError;
-	            }
-	          }
-	        }
 
+	          _this.drakesFor(name, drakes);
+	        });
 	        return this;
 	      }
 	    }, {
@@ -2213,42 +2028,21 @@ var require$$0$3 = Object.freeze({
 	          }, {});
 	        }
 
-	        var drakeNames = Object.keys(drakes);
-	        var _iteratorNormalCompletion2 = true;
-	        var _didIteratorError2 = false;
-	        var _iteratorError2 = undefined;
-
-	        try {
-	          for (var _iterator2 = drakeNames[Symbol.iterator](), _step2; !(_iteratorNormalCompletion2 = (_step2 = _iterator2.next()).done); _iteratorNormalCompletion2 = true) {
-	            var drakeName = _step2.value;
-
-	            var drakeOpts = drakes[drakeName];
-	            if (drakeOpts === true) {
-	              drakeOpts = {};
-	            }
-
-	            service.setOptions(drakeName, drakeOpts);
-	          }
-	        } catch (err) {
-	          _didIteratorError2 = true;
-	          _iteratorError2 = err;
-	        } finally {
-	          try {
-	            if (!_iteratorNormalCompletion2 && _iterator2.return) {
-	              _iterator2.return();
-	            }
-	          } finally {
-	            if (_didIteratorError2) {
-	              throw _iteratorError2;
-	            }
+	        Object.keys(drakes).forEach(function (drakeName) {
+	          var drakeOpts = drakes[drakeName];
+	          if (drakeOpts === true) {
+	            drakeOpts = {};
 	          }
-	        }
 
+	          service.setOptions(drakeName, drakeOpts);
+	        });
 	        return this;
 	      }
 	    }, {
 	      key: 'on',
 	      value: function on(name) {
+	        var _this2 = this;
+
 	        var handlerConfig = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
 
 	        logServiceConfig('on', name, handlerConfig);
@@ -2263,31 +2057,9 @@ var require$$0$3 = Object.freeze({
 	          }
 
 	          logServiceConfig('add event handlers for', serviceNames);
-	          var _iteratorNormalCompletion3 = true;
-	          var _didIteratorError3 = false;
-	          var _iteratorError3 = undefined;
-
-	          try {
-	            for (var _iterator3 = serviceNames[Symbol.iterator](), _step3; !(_iteratorNormalCompletion3 = (_step3 = _iterator3.next()).done); _iteratorNormalCompletion3 = true) {
-	              var serviceName = _step3.value;
-
-	              this.on(serviceName, handlerConfig);
-	            }
-	          } catch (err) {
-	            _didIteratorError3 = true;
-	            _iteratorError3 = err;
-	          } finally {
-	            try {
-	              if (!_iteratorNormalCompletion3 && _iterator3.return) {
-	                _iterator3.return();
-	              }
-	            } finally {
-	              if (_didIteratorError3) {
-	                throw _iteratorError3;
-	              }
-	            }
-	          }
-
+	          serviceNames.forEach(function (serviceName) {
+	            _this2.on(serviceName, handlerConfig);
+	          });
 	          return this;
 	        }
 
@@ -2593,33 +2365,14 @@ var require$$0$3 = Object.freeze({
 	  }, {
 	    key: 'updateModelRef',
 	    value: function updateModelRef() {
+	      var _this = this;
+
 	      // this.modelRef = mutable
 	      // this.log('set modelRef', this.modelRef, this.model)
 	      this.modelRef.splice(0, this.modelRef.length);
-	      var _iteratorNormalCompletion = true;
-	      var _didIteratorError = false;
-	      var _iteratorError = undefined;
-
-	      try {
-	        for (var _iterator = this.model[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
-	          var item = _step.value;
-
-	          this.modelRef.push(item);
-	        }
-	      } catch (err) {
-	        _didIteratorError = true;
-	        _iteratorError = err;
-	      } finally {
-	        try {
-	          if (!_iteratorNormalCompletion && _iterator.return) {
-	            _iterator.return();
-	          }
-	        } finally {
-	          if (_didIteratorError) {
-	            throw _iteratorError;
-	          }
-	        }
-	      }
+	      this.model.forEach(function (item) {
+	        _this.modelRef.push(item);
+	      });
 	    }
 	  }, {
 	    key: 'undo',
@@ -2736,12 +2489,6 @@ var require$$0$3 = Object.freeze({
 	      return new ImmutableModelManager(opts);
 	    }
 	  }, {
-	    key: 'at',
-	    value: function at(index) {
-	      console.log('find model at', index, this.model);
-	      return get(ImmutableModelManager.prototype.__proto__ || Object.getPrototypeOf(ImmutableModelManager.prototype), 'at', this).call(this, index);
-	    }
-	  }, {
 	    key: 'isEmpty',
 	    value: function isEmpty() {
 	      return this.model.length === 0;
```
</details>

### CODE REVIEW

**Comment by kristianmandrup** [comment]
Gracias!

**Comment by razh** [comment]
@kristianmandrup 👍  That was fast!

**Comment by kristianmandrup** [comment]
Would love if you could fix the demo as well. Needs keys `:key` on each list as of Vue 2.2 I think

**Comment by razh** [comment]
@kristianmandrup I'll take a look at it.

**Pull request merged**
